apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      labels:
        app: db-noticias
    spec:
      containers:
      - name: db-noticias-container
        image: aluracursos/mysql-db:1
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-configmap

--- 
apiVersion: v1
kind: Service
metadata:
  name: svc-db-noticias
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: db-noticias